haproxy:
    image: rsiws/haproxy
    links:
        - io_node1:io_node1
        - io_node2:io_node2
        - io_node3:io_node3
        - io_node4:io_node4
    ports:
        - "80:80"
io_node1:
    image: rsiws/messaging
    links:
        - redis
    ports:
        - "8080"
io_node2:
    image: rsiws/messaging
    links:
        - redis
    ports:
        - "8080"
io_node3:
    image: rsiws/messaging
    links:
        - redis
    ports:
        - "8080"
io_node4:
    image: rsiws/messaging
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"
