#nginx:
#    build: ./nginx
#    links:
#        - io_node1:io_node1
#        - io_node2:io_node2
#        - io_node3:io_node3
#    ports:
#        - "3000:3000"

haproxy:
    build: ./haproxy
    links:
        - io_node1:io_node1
        - io_node2:io_node2
        - io_node3:io_node3
    ports:
        - "3000:3000"

io_node1:
    build: ./node
    links:
        - redis
    ports:
        - "3000"
io_node2:
    build: ./node
    links:
        - redis
    ports:
        - "3000"
io_node3:
    build: ./node
    links:
        - redis
    ports:
        - "3000"
redis:
    image: redis
    ports:
        - "6379"
